### ISSUE TITLE
Inkscape Extension Windows 10

### ISSUE THREAD

**Issue by samputzi** [florianfesti/boxes#47] opened 2017-11-12 18:22 UTC
Hi can anybody explain how to get the Extensions workingf in Inkscape? I searched everywhere and also followed the Explenation from misiekkk but i cant get it working... has someone screenshots on how to make it? 

Thanks for every help

**Comment by florianfesti** [comment] 2017-11-20 08:39
I do not have Windows, but if you describe what you tried so far I might be able to give some hints. Does the Boxes.py Menu show up in Extensions?

**Comment by florianfesti** [comment] 2017-11-22 16:33
Ok, looking at Inkscape on Linux it seems like it really only looks in the current working dir and the extension directory (not even the other global/local extension dir). So you might need to copy the boxes script (from scripts/) in there beside the *.inx files. You might need to add the boxes module to your python path if it is not in there.
Adding
`sys.path.append("PATHTOBOXESMODULE")`
before the `import boxes` line in the boxes script may do the trick.

**Comment by deepinthewoods** [comment] 2018-01-22 16:58
I have got the extensions working from source now, here are the instructions. Starting from a fresh windows 10 64 bit install.

Install [inkscape](inkscape.org)
Install [python 3](https://www.python.org/downloads/windows/)  [(direct)](https://www.python.org/ftp/python/3.6.4/python-3.6.4-amd64.exe). Make sure you select the 64-bit python. Tick the "add to PATH" checkbox.
Restart

From cmd.exe:
`pip install svgutils`

Install the [C++ build tools](http://landinghub.visualstudio.com/visual-cpp-build-tools (long))
Install the [GTK3 Runtime](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases)  [(direct)](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases/download/2018-01-18/gtk3-runtime-3.22.26-2018-01-18-ts-win64.exe)

Restart
Run cmd.exe as admin: 
```
cd \
cd boxes-master
python setup.py build
python setup.py install
python scripts\boxes2inkscape inkex
```
Copy all .inx files from \inkex to ~\AppData\Roaming\inkscape\extensions folder
Copy boxes file from \scripts to extensions folder


Edit ~\AppData\Roaming\Inkscape\preferences.xml
Modify this section:
```
<group
     id="extensions"
```
to add this line with a link to your python.exe
```
<group
     id="extensions"
     python-interpreter="C:\Users\n\AppData\Local\Programs\Python\Python36\python.exe"
```
Make sure inkscape is closed before you edit this file or it will overwrite your changes

Edit the inx file that you want to use. change this line
`<command reldir="extensions">boxes</command>`
to
`<command reldir="extensions" interpreter="python">boxes</command>`

That's it! I couldn't get it to work with python2+win8.1. Everything appears in inkscape it just doesn't do anything when you click "apply". I had errors installing python3 in win8.1 so couldn't get any further.

**Comment by doktorinjh** [comment] 2018-06-16 19:55
Thanks for the walkthrough, but I'm getting stuck when I try to build setup.py. I'm getting "OSError: dlopen() failed to load a library: cairo / cairo-2" and I can't seem to get past it. Any thoughts?

**Comment by doktorinjh** [comment] 2018-06-21 13:52
I'll try again, but I think I did. Thanks!

**Comment by time4conquer** [comment] 2018-09-08 20:35
I am getting an error while performing above guidelines in Windows 8.1, Please help.

C:\boxes-master>python setup.py build
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'

**Comment by time4conquer** [comment] 2018-09-13 19:53
Actually i am using window 8.1, Can you please generate *.inx files for us so that we can copy from here. It would be very thankful to you.

**Comment by florianfesti** [comment] 2018-09-13 22:10
I'll build and upload them tomorrow. But they won't help you unless you get boxes.py working. If you have it working you should be able to just do `python scripts\boxes2inkscape inkex`.

**Comment by deepinthewoods** [comment] 2018-09-14 07:02
I made an exe file version. 8 months old and doesn't support writing your
own generators but here is the link
https://github.com/deepinthewoods/Boxes.py-Windows-Binaries

**Comment by florianfesti** [comment] 2018-09-14 10:59
Here are the inkex files. I hope that not too much private stuff sneaked in there...  
[boxes.inkex.zip](https://github.com/florianfesti/boxes/files/2383037/boxes.inkex.zip)

**Comment by time4conquer** [comment] 2018-09-15 11:05
I have tried to install this paste all .inx & .py files in Extensions folder however it doesn't work. Attached the files for reference. 
![boxes py error](https://user-images.githubusercontent.com/43011655/45585631-7a3c9600-b89c-11e8-91cd-528224472fb1.png)

**Comment by florianfesti** [comment] 2018-09-15 13:14
This is a result of Inkscape reading the .inx files but not finding the boxes script. You need a copy of scripts/boxes in the extensions directory. It is quite possible that this still won't work due to the different idea what Windows and proper operating script have about what executables are.
Here is an alternative set of inx files that tries to execute the script with python (as pointed out in https://github.com/florianfesti/boxes/issues/47#issuecomment-359491540 )
[boxes.inkex-2.zip](https://github.com/florianfesti/boxes/files/2385703/boxes.inkex-2.zip)

**Comment by mr-imaginativ3** [comment] 2019-02-20 00:06
Hello Mr. Festi

I love the possibilities offered by your boxes.py.

I carefully followed deepinthewoods windows instructions and read all comments so far. As far as I can tell nothing related directly to my issue.

When I get to  
`python setup.py build`
I get this error

`C:\boxes-master>python setup.py build
running build
running build_py
buildInkscapeExt()
Traceback (most recent call last):
  File "scripts\boxes2inkscape", line 29, in <module>
    import boxes.generators
ModuleNotFoundError: No module named 'boxes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts\boxes2inkscape", line 32, in <module>
    import boxes.generators
  File "scripts/..\boxes\__init__.py", line 23, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
error: [WinError 2] The system cannot find the file specified`

I am very novice to programming and currently studying Arduino programming. So as a novice I can't make heads or tails of what to do with lines where the errors are and what they mean.

Looking forward to making this work  and introducing this to the FabLab I belong to.

Mr. Imaginativ3

**Comment by deepinthewoods** [comment] 2019-02-20 10:10
Cairo is a part of gtk, are you sure you restarted your PC after installing GTK3? And are you running cmd.exe as administrator?

**Comment by mr-imaginativ3** [comment] 2019-02-20 13:13
Yes... I read that comment from before and made sure I did as you recommended
![boxes py](https://user-images.githubusercontent.com/47799625/53094141-5a626b80-34e7-11e9-8452-4d0aded48334.JPG)

**Comment by mr-imaginativ3** [comment] 2019-02-20 13:46
BTW C++ build tools link does not work

I don`t know if it makes a difference but the GTK (driect) link is not the latest GTK.
I installed the latest and tried the one from the direct link.
I get same result

**Comment by mr-imaginativ3** [comment] 2019-02-20 14:04
I just re-installed Python from the direct link and made sure I checked "add to PATH.
Same result.

My Windows 10 Home is all up to date according to "check for updates" app.

I am not sure what else I can do to cover my bases.

I am not going to freshly install Windows 10... too much work.
Anyways I don't have any other issues with all the apps I run so don't seem necessary.

**Comment by deepinthewoods** [comment] 2019-02-20 14:11
https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017
Try this link, and reinstall gtk after.

**Comment by mr-imaginativ3** [comment] 2019-02-20 15:43
All I need to install is the C ++ tools I imagine.

**Comment by mr-imaginativ3** [comment] 2019-02-20 16:01
Same result.

**Comment by mr-imaginativ3** [comment] 2019-02-20 16:02
![boxes py](https://user-images.githubusercontent.com/47799625/53105382-0a8f9e80-34ff-11e9-95d4-ede0dac6726f.JPG)

**Comment by deepinthewoods** [comment] 2019-02-21 18:40
Well this is not working on my fresh win10 install either. You may be able
to get it working by installing cairo and the other dependencies another
way. There is also a version of python2 that comes with inkscape, you could
try getting that one to work (I was overriding that by editing the
preferences.xml). I don't have the python skills to help you with any of
that though.

Right now my plan is just to use Ubuntu via WSL
https://github.com/QMonkey/wsl-tutorial
or a VM.

**Comment by muellermartin** [comment] 2019-02-28 00:16
There is a fresh guide for Windows 10: https://florianfesti.github.io/boxes/html/install/windows.html

**Comment by vmario89** [comment] 2019-11-12 17:19
Hi, at the moment i a trying to make boxes.py working with InkScape 0.92.4 on Windows. Seems that nobody made this working until now. 

I got the boxes.py server running on Windows and WSL - so far easy to do. But the problem is to create some service which can be called by InkScape then. @deepinthewoods did some cool stuff when he packed the Python stuff into single exe. he told me he did with PyInstaller. I tried to do this too now because the latest commit is from beginning 2018.

Maybe someone of you has an idea on how to put boxes.py successfully into a single exe? That will help to make it compatible to InkScape 0.92.4 on Windows (which is using Python 2,7). 

I put some (unclean) documentation of my yet tested installation steps here: https://github.com/deepinthewoods/Boxes.py-Windows-Binaries/issues/1#issuecomment-552636446. Please note that they are incomplete and some things are missing to make it work. Thats why i am looking for help.

regards, Mario

**Comment by Regayi** [comment] 2021-01-30 14:04
see how I managed to make Boxes.py work as Inkscape plugin extension https://youtu.be/200LhQcWuiU

![Inkscape Boxes Py](https://user-images.githubusercontent.com/78264859/106358432-d0e38700-6314-11eb-8a64-a678b5ee75bc.PNG)

**Comment by vmario89** [comment] 2021-01-30 23:34
great!

in additon to this: https://wiki.fablabchemnitz.de/display/IFM/Boxes.py#expand-KnownErrorswhenbuilding documents a bit how to compile recent boxes.py yourself.

**Comment by florianfesti** [comment] 2021-05-22 14:10
As libcairo got removed much of the discussion above is no longer relevant. I am closing this here. See #314 for the curretn develpments with Inkspace and Boxes.py on Windows.

**Closed by florianfesti** 2021-05-22 14:10 UTC
