### ISSUE TITLE
Slide On Lids for TypeTray mixed up

### ISSUE THREAD

**Issue by GBDownUnder** [florianfesti/boxes#502] opened 2023-01-15 04:31 UTC
**Describe the bug**
I just tried making two TypeTray boxes with slide on lids.  One for 53x2 & 65x2 (SetupA) and one for 65x2 & 53x2 (SetupB).
The lid in each generation is the one for the other one.  
ie SetUpA creates a lid which is "wide" while the box is "long".
ie SetUpB creates a lid which is "long" while the box is "wide".

If you print both and swap lids you end up with two correct boxes.

**To Reproduce**
See Describe the bug
Create this box and see image attached for the issue
https://tinyurl.com/5ehaezyp

**Expected behavior**
A wide box makes a wide lid, a narrow box makes a narrow lid.

**Screenshots or Drawings**
![CAPTURE3](https://user-images.githubusercontent.com/33711702/212522982-72809a6c-1bc4-4690-9af0-6522a0630923.jpg)

**Comment by florianfesti** [comment] 2023-01-16 14:36
Duplicate of #469

**Closed by florianfesti** 2023-01-16 14:36 UTC
Labels: bug
