### ISSUE TITLE
Proxy Error only for TypeTray

### ISSUE THREAD

**Issue by alexbn71** [florianfesti/boxes#450] opened 2022-10-24 05:17 UTC
Hi, this page: https://www.festi.info/boxes.py/TypeTray?language=en

return:

`Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /boxes.py/TypeTray.

Reason: Error reading from remote server

Apache/2.4.6 (CentOS) Server at www.festi.info Port 443`

**Comment by florianfesti** [comment] 2023-01-01 10:07
Duplicate of #440

**Closed by florianfesti** 2023-01-01 10:07 UTC
Labels: bug
