### ISSUE TITLE
Three and Four Join edge "Duckbill Joint" 

### ISSUE THREAD

**Issue by christensonb** [florianfesti/boxes#217] opened 2020-04-06 14:50 UTC
![image](https://user-images.githubusercontent.com/9574013/78570644-dbafb700-77ea-11ea-9c03-80852168cbba.png)

I think a really cool edge would be a wide dovetail that has holes like
![image](https://user-images.githubusercontent.com/9574013/78571174-858f4380-77eb-11ea-8b03-aadd06c6b323.png)

if we make the fingers with a slight  widening and we put a slit  from the hole to the edge of the dove tail.  Then as you push the fingers in it would make the dove tail joint even tighter.

I will draw something up to show my intent

**Comment by christensonb** [comment] 2020-04-06 15:04
![image](https://user-images.githubusercontent.com/9574013/78573181-08b19900-77ee-11ea-840d-637a42d0005f.png)

**Comment by christensonb** [comment] 2020-04-06 15:15
So this would allow for a three piece joint, and to do the four piece joint I would simply do the three piece every other hole so each of them share the holes.

**Comment by christensonb** [comment] 2020-04-07 04:43
I created some code and it is looking pretty good but I definitely could use some help.
https://github.com/SeabornGames/boxes/blob/duckbill_joint/boxes/edges.py#L1836

It currently doesn't work for even number of tabs, and the DuckbillJointCountnerPart doesn't draw the holes for reasons I can't figure out.

The whole thing probably doesn't scale.

**Comment by christensonb** [comment] 2020-04-07 04:46
[Archive.zip](https://github.com/florianfesti/boxes/files/4442081/Archive.zip)
![image](https://user-images.githubusercontent.com/9574013/78631003-bb224400-7860-11ea-820e-3f21b6f93952.png)

**Comment by florianfesti** [comment] 2020-04-07 07:25
I am not quite sure if this solves the right problem (What ever this means). Dovetail joints are only really needed if you bend walls around some object like in RoundedBox. For all other cases you can just make the wall from one piece.

The issue is jointing the other two walls at the some spot - which is something this solution doesn't provide. But may be I am just not getting the problem you are trying to solve.

What about having a FingerHole pattern that allows inserting walls from both sides?

**Comment by christensonb** [comment] 2020-04-07 13:52
I couldn't follow the clockwise counter clockwise issue, but is that why the holes doesn't showup on the right side

**Comment by christensonb** [comment] 2020-04-07 13:57
So if I number the image above from top left to bottom right
1 2
3 4
5 6

Then I could connect 1, 2 and 5 together to make a T intesect.
Alternatively I could connect 3, 4, 5, 6 together to form a +

The problem with assuming you could build it with one long wall is that my glowforge laser printer is only so big.

**Comment by christensonb** [comment] 2020-04-07 13:58
remember 2 is missing the holes that 5 has, and that is a problem I am asking help with.

**Comment by christensonb** [comment] 2020-04-08 01:19
I have mostly solved it
![image](https://user-images.githubusercontent.com/9574013/78734126-042fd200-790d-11ea-80a5-2708c28fd3f4.png)

Do I have to use the radius?

**Comment by christensonb** [comment] 2020-04-08 03:50
https://lh3.googleusercontent.com/-9koQB6EZn4U/Xo00DWdg-2I/AAAAAAAAq8Q/_AC1AzIhXGkiOR4KI3bRmfkga5hGhr34ACK8BGAsYHg/s0/2020-04-07

**Comment by christensonb** [comment] 2020-04-08 03:58
![image](https://user-images.githubusercontent.com/9574013/78743120-554ac080-7923-11ea-92a5-2501878e851e.png)

**Comment by christensonb** [comment] 2020-04-08 03:59
![image](https://user-images.githubusercontent.com/9574013/78743140-61cf1900-7923-11ea-96ea-dd3029f9b3bf.png)

**Comment by christensonb** [comment] 2020-04-08 03:59
![image](https://user-images.githubusercontent.com/9574013/78743151-685d9080-7923-11ea-99cf-11c9c0a2d88e.png)

**Comment by florianfesti** [comment] 2020-04-08 09:03
The joint would be even stronger if you made the holes not part of the outline. Just put some rectagularHole() there. You can even do that directly before drawing the straight line on the outside of the dove tail to save you the math.

**Comment by florianfesti** [comment] 2021-06-05 12:35
I am still kinda missing a good use case. I really don't see why the dovetail joint would be needed there. May be doing less is more and just have a `-|-` joint is more useful.

Closing this for now.

**Closed by florianfesti** 2021-06-05 12:35 UTC
