### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by leonelbanegas** [florianfesti/boxes#449] opened 2022-10-20 00:22 UTC
**Describe the bug**
the page gives an error to the generate a universal box

**To Reproduce**
[If possible give an URL or command line that leads to the issue. If possible try to reproduce the issue on the public web instance.](https://www.festi.info/boxes.py/UniversalBox)

**Expected behavior**
.

**Screenshots or Drawings**
![image](https://user-images.githubusercontent.com/24424146/196828490-020aaba8-7b44-4a5f-b29a-29f102c54caa.png)

**Additional context**

**Comment by florianfesti** [comment] 2022-12-31 12:53
Duplicate of #440

**Closed by florianfesti** 2022-12-31 12:53 UTC
Labels: bug
